/*
 * generated by Xtext
 */
package org.modelexecution.fumltesting.uml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.modelexecution.fumltesting.uml.ui.internal.UmlTestLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UmlTestLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return UmlTestLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return UmlTestLangActivator.getInstance().getInjector(UmlTestLangActivator.ORG_MODELEXECUTION_FUMLTESTING_UML_UMLTESTLANG);
	}
	
}
