<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sequence" nsURI="http://www.modelexecution.org/sequence" nsPrefix="sequence">
  <eClassifiers xsi:type="ecore:EClass" name="SequenceTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" upperBound="-1"
        eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eOperations name="addState">
      <eParameters name="state" eType="#//State"/>
    </eOperations>
    <eOperations name="lastState" eType="#//State"/>
    <eOperations name="firstState" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityExecution" lowerBound="1"
        eType="ecore:EClass ../../org.modelexecution.fumldebug.core/model/tracemodel.ecore#//ActivityExecution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass ../../org.modelexecution.fuml/model/fUML.ecore#//Semantics/Classes/Kernel/Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="ecore:EClass ../../org.modelexecution.fuml/model/fUML.ecore#//Semantics/Classes/Kernel/Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" eType="#//State"
        eOpposite="#//State/predecessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" eType="#//State"
        eOpposite="#//State/successor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeExecution" lowerBound="1"
        eType="ecore:EClass ../../org.modelexecution.fumldebug.core/model/tracemodel.ecore#//ActivityNodeExecution"/>
  </eClassifiers>
</ecore:EPackage>
