/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.xmof.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.modelexecution.fumltesting.xmof.services.XmofTestLangGrammarAccess;

public class XmofTestLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XmofTestLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.modelexecution.fumltesting.xmof.parser.antlr.internal.InternalXmofTestLangParser createParser(XtextTokenStream stream) {
		return new org.modelexecution.fumltesting.xmof.parser.antlr.internal.InternalXmofTestLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "XMOFTestSuite";
	}
	
	public XmofTestLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XmofTestLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
