/*
 * generated by Xtext
 */
package org.modelexecution.fumltesting.xmof.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.modelexecution.fumltesting.xmof.ui.internal.XmofTestLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XmofTestLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XmofTestLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XmofTestLangActivator.getInstance().getInjector(XmofTestLangActivator.ORG_MODELEXECUTION_FUMLTESTING_XMOF_XMOFTESTLANG);
	}
	
}
