/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.xmof;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XmofTestLangStandaloneSetup extends XmofTestLangStandaloneSetupGenerated{

	public static void doSetup() {
		new XmofTestLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

