/*
 * generated by Xtext
 */
package org.modelexecution.fumltesting.xmof;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XmofTestLangRuntimeModule extends org.modelexecution.fumltesting.xmof.AbstractXmofTestLangRuntimeModule {

}
