/*
 * generated by Xtext
 */
package org.modelexecution.fumltesting.xmof.ui.contentassist

import org.modelexecution.fumltesting.xmof.ui.contentassist.AbstractXmofTestLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XmofTestLangProposalProvider extends AbstractXmofTestLangProposalProvider {
}
