/*
 * generated by Xtext
 */
package org.modelexecution.fumltesting.uml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UmlTestLangUiModule extends org.modelexecution.fumltesting.uml.ui.AbstractUmlTestLangUiModule {
	public UmlTestLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
