<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testLang" nsURI="http://www.modelexecution.org/fumltesting/TestLang"
    nsPrefix="testLang">
  <eClassifiers xsi:type="ecore:EClass" name="TestSuite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="#//TestCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//ObjectNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityUnderTest" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//ActivityInput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextObject" eType="#//ObjectSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initScenarios" unique="false"
        upperBound="-1" eType="#//Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//VarDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertions" upperBound="-1"
        eType="#//Assertion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//ActivityParameterNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectValue" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ObjectSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//ObjectSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="att" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assoc" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceProperty" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceValue" eType="#//ObjectSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetProperty" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetValue" eType="#//ObjectSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporalQuantifier" eType="#//TemporalQuantifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporalOperator" eType="#//TemporalOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceAction" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="untilAction" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" unique="false"
        upperBound="-1" eType="ecore:EClass ../../../../../org.eclipse.ocl.examples.xtext.essentialocl/model/EssentialOCLCST.ecore#//ExpCS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//StateExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinallyStateAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//StateExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin" eType="#//VarDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//ArithmeticOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectStateExpression" eSuperTypes="#//StateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyStateExpression" eSuperTypes="#//StateExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderAssertion" eSuperTypes="#//Assertion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="order" eType="#//NodeOrder"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeOrder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//NodeSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="ecore:EClass ../../../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subOrder" eType="#//NodeOrder"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="joker" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperator">
    <eLiterals name="equal" literal="="/>
    <eLiterals name="not_equal" value="1" literal="!="/>
    <eLiterals name="greater" value="2" literal=">"/>
    <eLiterals name="smaller" value="3" literal="&lt;"/>
    <eLiterals name="greater_equal" value="4" literal=">="/>
    <eLiterals name="smaller_equal" value="5" literal="&lt;="/>
    <eLiterals name="includes" value="6" literal="includes"/>
    <eLiterals name="excludes" value="7" literal="excludes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TemporalOperator">
    <eLiterals name="after" literal="after"/>
    <eLiterals name="before" value="1" literal="before"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TemporalQuantifier">
    <eLiterals name="exactly" literal="exactly"/>
    <eLiterals name="always" value="1" literal="always"/>
  </eClassifiers>
</ecore:EPackage>
