/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TestLangOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
