/*
 * generated by Xtext
 */
package org.modelexecution.fumltesting;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestLangRuntimeModule extends org.modelexecution.fumltesting.AbstractTestLangRuntimeModule {

}
