/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.xmof;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XmofTestLangUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.modelexecution.fumltesting.xmof.ui.internal.XmofTestLangActivator.getInstance().getInjector("org.modelexecution.fumltesting.xmof.XmofTestLang");
	}
	
}
