/*
 * generated by Xtext
 */
package org.modelexecution.fumltesting.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TestLangUiModule extends org.modelexecution.fumltesting.ui.AbstractTestLangUiModule {
	public TestLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
