/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TestLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/modelexecution/fumltesting/parser/antlr/internal/InternalTestLang.tokens");
	}
}
