/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.modelexecution.fumltesting.services.TestLangGrammarAccess;

public class TestLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TestLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.modelexecution.fumltesting.parser.antlr.internal.InternalTestLangParser createParser(XtextTokenStream stream) {
		return new org.modelexecution.fumltesting.parser.antlr.internal.InternalTestLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "UMLTestSuite";
	}
	
	public TestLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TestLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
