/*
 * generated by Xtext
 */
package org.modelexecution.fumltesting.uml.ui.contentassist

import org.modelexecution.fumltesting.uml.ui.contentassist.AbstractUmlTestLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class UmlTestLangProposalProvider extends AbstractUmlTestLangProposalProvider {
}
