/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.uml;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class UmlTestLangStandaloneSetup extends UmlTestLangStandaloneSetupGenerated{

	public static void doSetup() {
		new UmlTestLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

