/*
 * generated by Xtext
 */
package org.modelexecution.fumltesting.xmof.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XmofTestLangUiModule extends org.modelexecution.fumltesting.xmof.ui.AbstractXmofTestLangUiModule {
	public XmofTestLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
