/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.ui.contentassist;

import org.modelexecution.fumltesting.ui.contentassist.AbstractTestLangProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TestLangProposalProvider extends AbstractTestLangProposalProvider {

}
