/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.uml.validation;

import java.util.HashSet;

import org.eclipse.xtext.validation.Check;
import org.modelexecution.fumltesting.uml.umlTestLang.UMLNodeSpecification;
import org.modelexecution.fumltesting.uml.umlTestLang.UMLOrderAssertion;
import org.modelexecution.fumltesting.uml.umlTestLang.UMLScenario;
import org.modelexecution.fumltesting.uml.umlTestLang.UMLStateAssertion;
import org.modelexecution.fumltesting.uml.umlTestLang.UMLTemporalOperator;
import org.modelexecution.fumltesting.uml.umlTestLang.UMLTestCase;
import org.modelexecution.fumltesting.uml.umlTestLang.UmlTestLangPackage;

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class UmlTestLangJavaValidator extends AbstractUmlTestLangJavaValidator {
	@Check
	public void checkAfterSpecified(UMLStateAssertion assertion) {
		if (assertion.getOperator() == UMLTemporalOperator.UNTIL && assertion.getUntilPoint() != null) {
			warning("Subsequent usage of UNTIL is not allowed!", UmlTestLangPackage.Literals.UML_STATE_ASSERTION__UNTIL_POINT);
		}
	}

	@Check
	public void checkUseOfJokers(UMLOrderAssertion assertion) {
		boolean subsequentStarUsed = false;
		for (UMLNodeSpecification nodeSpecification : assertion.getOrder().getNodes()) {
			if (nodeSpecification.getJoker() != null && nodeSpecification.getJoker().equals("*")) {
				int nextNodeIndex = assertion.getOrder().getNodes().indexOf(nodeSpecification) + 1;
				if (assertion.getOrder().getNodes().size() > nextNodeIndex
						&& assertion.getOrder().getNodes().get(nextNodeIndex).getJoker().equals("*"))
					subsequentStarUsed = true;
			}
		}
		if (subsequentStarUsed)
			error("Use of subsequent STAR is not allowed!", UmlTestLangPackage.Literals.UML_ORDER_ASSERTION__ORDER);
	}

	@Check
	public void checkScenarioInitialize(UMLTestCase testCase) {
		HashSet<UMLScenario> set = new HashSet<UMLScenario>(testCase.getInitScenarios());
		if (testCase.getInitScenarios().size() > set.size())
			error("Test scenario declared more than once!", UmlTestLangPackage.Literals.UML_TEST_CASE__INIT_SCENARIOS);
	}
}