/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.uml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UmlTestLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/modelexecution/fumltesting/uml/parser/antlr/internal/InternalUmlTestLang.tokens");
	}
}
