/*
* generated by Xtext
*/
package org.modelexecution.fumltesting.uml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.modelexecution.fumltesting.uml.services.UmlTestLangGrammarAccess;

public class UmlTestLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UmlTestLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.modelexecution.fumltesting.uml.parser.antlr.internal.InternalUmlTestLangParser createParser(XtextTokenStream stream) {
		return new org.modelexecution.fumltesting.uml.parser.antlr.internal.InternalUmlTestLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "UMLTestSuite";
	}
	
	public UmlTestLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UmlTestLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
